<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-07T16:39:15Z" name="pl.imgw.tests.DownloadWeatherDataTest" finished-at="2021-10-07T16:39:15Z" duration-ms="69">
    <groups>
    </groups>
    <test started-at="2021-10-07T16:39:15Z" name="Command line test" finished-at="2021-10-07T16:39:15Z" duration-ms="69">
      <class name="pl.imgw.tests.DownloadWeatherDataTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0]" started-at="2021-10-07T16:39:15Z" name="setUp" finished-at="2021-10-07T16:39:15Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="checkIfFileIsAlreadyCreated()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0]" started-at="2021-10-07T16:39:15Z" name="checkIfFileIsAlreadyCreated" finished-at="2021-10-07T16:39:15Z" duration-ms="29" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[File C://Users//urban//OneDrive//Documents//imgw//2021-10-07_jeleniagora.jsonis already created expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: File C://Users//urban//OneDrive//Documents//imgw//2021-10-07_jeleniagora.jsonis already created expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at pl.imgw.tests.DownloadWeatherDataTest.checkIfFileIsAlreadyCreated(DownloadWeatherDataTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkIfFileIsAlreadyCreated -->
        <test-method signature="getApiData()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0]" started-at="2021-10-07T16:39:15Z" name="getApiData" finished-at="2021-10-07T16:39:15Z" depends-on-methods="pl.imgw.tests.DownloadWeatherDataTest.checkIfFileIsAlreadyCreated" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadWeatherDataTest.getApiData()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadWeatherDataTest.getApiData()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApiData -->
        <test-method signature="saveFile()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0]" started-at="2021-10-07T16:39:15Z" name="saveFile" finished-at="2021-10-07T16:39:15Z" depends-on-methods="pl.imgw.tests.DownloadWeatherDataTest.getApiData" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadWeatherDataTest.saveFile()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadWeatherDataTest.saveFile()[pri:0, instance:pl.imgw.tests.DownloadWeatherDataTest@36b4cef0] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveFile -->
      </class> <!-- pl.imgw.tests.DownloadWeatherDataTest -->
    </test> <!-- Command line test -->
  </suite> <!-- pl.imgw.tests.DownloadWeatherDataTest -->
</testng-results>
